### ISSUE TITLE
g++ not found on all `nix systems

### ISSUE THREAD

**Issue by jeffsf** [zorun/kea-hook-runscript#1]
In trying to compile under FreeBSD 11.1, the gnu toolchain is not installed and `g++` as a compiler invocation fails. `c++` _should_ work on most current `nix, especially those that use an "alternatives" approach.

Holding off on a patch, as it's trivial and I'm working through other `make` issues.

**Comment by zorun** [comment]
Cool, thanks for looking into it!  I'm not against switching to autotools, it's just that I don't want to spend time on it.  Feel free to send a patch if you know how these things work.

**Comment by jeffsf** [comment]
No problem. I think that staying away from autotools when possible keeps everyone sane! In this case, it should be just changing `g++` to `c++` the couple places it occurs. Major thanks for writing this! Once I get it to compile under FreeBSD, I'll upload a clean set of patches.

**Comment by zorun** [comment]
Hi @jeffsf , any news on this issue?

**Comment by zorun** [comment]
Fixed in 687fbe23c879be2f027c548cadb54a108c2b3315 .  Please open a new issue if you encounter further issues building this on FreeBSD.
