### ISSUE TITLE
Add build artifacts

### ISSUE THREAD

**Issue by jgroom33** [zorun/kea-hook-runscript#14]
CI should build a binary for each: kea release + hook-runscript

**Comment by zorun** [comment]
That sounds like a good idea because it can be a pain to build, but I have no time to invest in that.

I'll happily accept patches.

**Comment by zorun** [comment]
Done, see https://github.com/zorun/kea-hook-runscript/releases/tag/v1.4.0

I'll leave this open for a while for feedback.
