### ISSUE TITLE
Kea 1.6.3 - the status-get backport

### ISSUE THREAD

**Issue by nevada-american** [zorun/kea-hook-runscript#20]
Not so much an issue, as an advisory. Kea 1.6.3 will require rebuilding this hook library.  In dev testing, kea-dhcp4 will not load the library (compiled based off the 1.6.2 reference tree).  Also I never seem to end up with kea-msg-compiler from the ISC Cloudsmith repos (requiring the extra step of compiling that part of the kea source).

Solution: Grab 1.6.3 source, build as required, then follow existing instructions to build this hook library.  Kea 1.6.3 will at least now start with the library referenced in the config.  Further testing is ongoing (we use for DDNS -> Active Directory updates), but it should Just Work.

**Comment by zorun** [comment]
Yes, the hook should always be built with the exact same version of Kea as the one you will run it with.
