### ISSUE TITLE
Multi-threading support in 1.9.x

### ISSUE THREAD

**Issue by korekhov** [zorun/kea-hook-runscript#23]
As README stated, I'm creating a ticket for adding multi-threading support in 1.9.x.

**Comment by zorun** [comment]
Please elaborate on your use-case and how you imagine things working (locking in the hook? in the script?)

**Comment by korekhov** [comment]
Well, I may have jumped a gun here creating this issue.

I've installed your hook yesterday (with disabled multithreading) on my lab 1.9.x KEA instance to try it out with your debug script to log all of the events (hook points) that are happening - works great so far. However, I found that events that I was looking for and hoping to trigger on are not logged - subnet creation/deletion (through API call). The idea is to automatically create and/or delete DNS entries for each of the DHCP pool member in a subnet. 

If no such hook event/point exists, we can close this issue all together.

**Comment by zorun** [comment]
Ok, then please open a separate issue if you need more hook points. I only implemented the ones related to pkt and lease processing, the full list is here:
https://jenkins.isc.org/job/Kea_doc/doxygen/de/df3/dhcpv4Hooks.html
https://jenkins.isc.org/job/Kea_doc/doxygen/d1/d02/dhcpv6Hooks.html

**Comment by korekhov** [comment]
According to KEA devs, there's no direct hook point that would help me with subnet creation/deletion. The only way to do so is through parsing through a series of events (a sequence of dhcp4_srv_configured and command_processed) to figure out what exactly happened as these 2 events are happening in a vast variety of cases, as you can imagine.

For what I was trying to achieve it is just an overkill, so I'm not going to pursue that directly.

Although adding those 2 hook points to your hook maybe beneficial for other purposes, but I'll leave it to you to decide whether to do it or not.

Thanks!
