### ISSUE TITLE
Option82

### ISSUE THREAD

**Issue by borg-z** [zorun/kea-hook-runscript#3]
Please, can you add option82 field? I was find code example at this repo https://github.com/Olen/kea_hooks

**Comment by borg-z** [comment]
https://gist.github.com/borgkun/2faae5e422ca5306f827c3b397c79111
Output: 
`KEA_RESPONSE4_RELAYED=1
KEA_QUERY4_OPTIONS=type=082, len=014:,
options:
  type=002, len=012: 02:0a:00:00:0a:6f:de:01:03:08:0e:26
`
But I do not know C ++, can you write a normal code?

**Comment by jmoore2016** [comment]
Hello, I also would like to see the ability to pass option 82 as a variable.

**Comment by salanki** [comment]
@borgkun: Submit your patch as a PR, will make it easier for the maintainer to merge it.

**Comment by zorun** [comment]
@borgkun @jmoore2016  I have no idea what option 82 is, can you elaborate on the format you expect? Is it just plain hexadecimal?

**Comment by jmoore2016** [comment]
@zorun

DHCP option 82 has suboptions. The suboptions are in HEX and we would need to pass on individual variables for each suboptions type. A deep dive into the suboptions can be found here:

http://www.firewall.cx/cisco-technical-knowledgebase/cisco-switches/1218-dhcp-snooping-option-82-relay-agent-message-format-analysis.html#dhcp-option-82-message-format

Please let me know ASAP on the feasibility of adding this variable as it would be incredibly useful to perform programmatic actions based on the relay info called out in option 82.

**Comment by zorun** [comment]
@jmoore2016 ok, thanks. I have also found the RFC https://tools.ietf.org/html/rfc3046#section-2.0

I don't have time to dive into that, but I would gladly review a patch that adds basic parsing of option 82.

Based on https://tools.ietf.org/html/rfc3046#section-3.0 no attempt should be made to decode the value itself. For variable names, something like this should be fine:

`KEA_QUERY4_OPT82_SUBOPT1`, `KEA_QUERY4_OPT82_SUBOPT2`, etc

Then `KEA_RESPONSE4_OPT82_SUBOPT1` if the option is present in a response, and the same thing for IPv6.

For the value of each variable, a simple hex-encoding is best.

**Comment by zorun** [comment]
Added in v1.4.0 via #22, thanks @joostbekkers !

See https://github.com/zorun/kea-hook-runscript/releases/tag/v1.4.0
