### ISSUE TITLE
Zombi processes

### ISSUE THREAD

**Issue by S7ran93r** [zorun/kea-hook-runscript#6]
When  parameter "wait" set to false,   kea-hook-runscript don't read return code of script,
and leave script in zombie state.

**Comment by zorun** [comment]
@salanki do you have any idea on the "zombie state" thing when running the script in the background?

**Comment by salanki** [comment]
I fixed this a while ago but I must have forgotten to actually open the PR. #7 fixes it.

**Comment by zorun** [comment]
Thanks, merged!
