### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by vekli** [zorun/kea-hook-runscript#8]
System description:
Ubuntu 16.04.5 LTS
kea 1.5.0
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11)

Error:
kea-msg-compiler -d src/ src/messages.mes
touch s-messages
g++ -MMD -MP -c -I /usr/include/kea -fPIC -Wno-deprecated -o src/messages.o src/messages.cc
g++ -MMD -MP -c -I /usr/include/kea -fPIC -Wno-deprecated -o src/logger.o src/logger.cc
g++ -MMD -MP -c -I /usr/include/kea -fPIC -Wno-deprecated -o src/load.o src/load.cc
src/load.cc:8:22: error: ‘data’ is not a namespace-name
 using namespace isc::data;
                      ^
src/load.cc:8:26: error: expected namespace-name before ‘;’ token
 using namespace isc::data;
                          ^
src/load.cc: In function ‘int load(isc::hooks::LibraryHandle&)’:
src/load.cc:21:5: error: ‘ConstElementPtr’ was not declared in this scope
     ConstElementPtr script = handle.getParameter("script");
     ^
src/load.cc:22:10: error: ‘script’ was not declared in this scope
     if (!script) {
          ^
src/load.cc:26:9: error: ‘script’ was not declared in this scope
     if (script->getType() != Element::string) {
         ^
src/load.cc:26:30: error: ‘Element’ has not been declared
     if (script->getType() != Element::string) {
                              ^
src/load.cc:30:19: error: ‘script’ was not declared in this scope
     script_path = script->stringValue();
                   ^
src/load.cc:33:21: error: expected ‘;’ before ‘wait’
     ConstElementPtr wait = handle.getParameter("wait");
                     ^
src/load.cc:34:14: error: expected primary-expression before ‘)’ token
     if (!wait) {
              ^
src/load.cc:36:20: error: expected primary-expression before ‘->’ token
     } else if (wait->getType() != Element::boolean) {
                    ^
src/load.cc:36:35: error: ‘Element’ has not been declared
     } else if (wait->getType() != Element::boolean) {
                                   ^
src/load.cc:40:26: error: expected primary-expression before ‘->’ token
        script_wait = wait->boolValue();
                          ^
Solution:
In Makefile need to add option  "-std=c++11"
>CXXFLAGS = -I $(KEA_INCLUDE) -fPIC -Wno-deprecated   -std=c++11

Also need to change env
  >"export KEA_MSG_COMPILER=/home/user/kea/src/lib/log/compiler/kea-msg-compiler"
  >"export KEA_INCLUDE=/home/user/kea/src/lib"
  >"export KEA_LIB=/usr/local/lib"

I hope it can be helpful for somebody.

**Comment by zorun** [comment]
Thanks, I've fixed the C++11 issue with older compilers in de66afdef8c512fced2e528600fa6c7adbd2f5f0.

For the environment variables, this is already documented in the README.
